name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
          cache: true
      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          # version: latest
          version: '~> v2'
          args: release --rm-dist
        env:
          # Custom secret here since we need to access to robinmin/homebrew-tap and robinmin/scoop-bucket repo.
          GITHUB_TOKEN: ${{ secrets.PBLSH_TOKEN }}
          SCOOP_TOKEN: ${{ secrets.PBLSH_TOKEN }}
